with open("goals.md", "w") as f:
    f.write("# Sustainable Development Goals\n\n")
    f.write("1. [No Poverty](https://sdgs.un.org/goals/goal1)\n")
    f.write("2. [Zero Hunger](https://sdgs.un.org/goals/goal2)\n")
    f.write("3. [Good Health and Well-being](https://sdgs.un.org/goals/goal3)\n")
    f.write("4. [Quality Education and Opportunities](https://sdgs.un.org/goals/goal4/)\n")
    f.write("5. [Gender Equality](https://sdgs.un.org/goals/goal5)\n")
    f.write("6. [Clean Water and Sanitation](https://sdgs.un.org/goals/goal6)\n")
    f.write("7. [Affordable and Clean Energy](https://sdgs.un.org/goals/goal7)\n")
    f.write("8. [Decent Work and Economic Growth](https://sdgs.un.org/goals/goal8)\n")
    f.write("9. [Industry, Innovation and Infrastructure](https://sdgs.un.org/goals/goal9)\n")
    f.write("10. [Reduced Inequalities](https://sdgs.un.org/goals/goal10)\n")
    f.write("11. [Sustainable Cities and Communities](https://sdgs.un.org/goals/goal11)\n")
    f.write("12. [Responsible Consumption and Production](https://sdgs.un.org/goals/goal2)\n")
    f.write("13. [Climate Change](https://sdgs.un.org/goals/goal3)\n")
    f.write("14. [Life Below Water](https://sdgs.un.org/goals/goal4)\n")
    f.write("15. [Life on Land](https://sdgs.un.org/goals/goal5)\n")
    f.write("16. [Peace, Justice and Strong Institutions](https://sdgs.un.org/goals/goal16)\n")
    f.write("17. [Partnership for the Goals](https://sdgs.un.org/goals/goal17)\n")
